{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crowdrender-agent.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "crowdrender-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range untilStep (.Values.service.ports.startport | int) (.Values.service.ports.endport | int) 1 }}
    - port: {{ . }}
      targetPort: p{{.}}
      {{- if eq $root.Values.service.type "NodePort" }}
      nodePort: {{ add . (sub $root.Values.service.nodePortStartPort $root.Values.service.ports.startport)}}
      {{- end }}
      protocol: TCP
      name: p{{.}}
    {{- end }}
  selector:
    {{- include "crowdrender-agent.selectorLabels" . | nindent 4 }}
