apiVersion: v1
kind: Service
metadata:
  name: {{ include "crowdrender-agent.fullname" . }}
  labels:
    {{- include "crowdrender-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range untilStep (.Values.service.ports.startport | int) (.Values.service.ports.endport | int) 1 }}
    - port: {{ . }}
      targetPort: p{{.}}
      protocol: TCP
      name: p{{.}}
    {{- end }}
  selector:
    {{- include "crowdrender-agent.selectorLabels" . | nindent 4 }}
